### ISSUE TITLE
CRITICAL: Task 4

### ISSUE THREAD

**Issue by egordya** [johanneslindq/TDA553-lab2#3]
Q1. `Since they both use the same methods the contracts are equally strong you could 
argue that it follows Liskov Substitution Principle, however since Scania and Volvo contain different attributes and methods apart from gas() and break() 
you can’t freely swap them out unless the program only uses methods that are shared among them (like gas() and break()).`

You are almost correct. **The contract for gas() in Vehicle is "Increases the speed of 
the vehicle if vehicle is in a state where it can move, otherwise does 
nothing."** 
Liskov Substitution Principle (LSP) does not apply to methods that are shared among different classes.

**Comment by johanneslindq** [comment]
Is this better?

**Comment by egordya** [comment]
Yes, but remove
`as all the subclasses from vehicle, share the gas/brake methods.`
See the comment above. 

Don't forget to make a tag for each submission and I haven't seen you make a submission of lab 3 on canvas. Make sure you do that if you have accidentally missed it :)
